from time import sleep
from colorama import Fore, Back, Style
from colorama import init
init()
# from py import diapason, warning

class graphics():


    def intro(self):
        print(Fore.WHITE + "  ╔╦╗╦═╗╦ ╦  ╔╦╗╔═╗  ╔═╗╦ ╦╔═╗╔═╗╔═╗  " + Style.RESET_ALL)
        print(Fore.BLUE +  "   ║ ╠╦╝╚╦╝   ║ ║ ║  ║ ╦║ ║║╣ ╚═╗╚═╗  " + Style.RESET_ALL)  
        print(Fore.RED +   "   ╩ ╩╚═ ╩    ╩ ╚═╝  ╚═╝╚═╝╚═╝╚═╝╚═╝  " + Style.RESET_ALL)
        print(Fore.CYAN + "              ╔═╗╔═╗╔╦╗╔═╗            " + Style.RESET_ALL)
        print(Fore.CYAN + "              ║ ╦╠═╣║║║║╣             "  + Style.RESET_ALL)  
        print(Fore.CYAN + "              ╚═╝╩ ╩╩ ╩╚═╝            " + Style.RESET_ALL)   
        print("\n\n loading", end="")
        for i in range(4):
            sleep(0.5)
            print(".", end="")                                                                                   
    def main_character(self, text):
        print(Fore.CYAN + ':"""""""""""""":    ' + "" + Fore.GREEN + '       ,-.' + Style.RESET_ALL)
        print(''' {0}               '''.format(text))
        print(Fore.CYAN + ":..............:_  " + "" + Fore.GREEN + "    .--'   |" + Style.RESET_ALL)
        print(Fore.GREEN + "                 '    /       /" + Style.RESET_ALL)
        print(Fore.GREEN + "                      |_______|" + Style.RESET_ALL)
        print(Fore.GREEN + "                     (  O   O  )" + Style.RESET_ALL)
        print(Fore.GREEN + "                      {'-(_)-'}" + Style.RESET_ALL)
        print(Fore.GREEN + "                    .-{   ^   }-." + Style.RESET_ALL)
        print(Fore.GREEN + '''                   /   '.___.'   \ ''' + Style.RESET_ALL)
        print(Fore.GREEN + '''                  /  |    o    |  \ ''' + Style.RESET_ALL)
        print(Fore.GREEN + "                  |__|    o    |__|" + Style.RESET_ALL)
        print(Fore.GREEN + "                  (((\_________/)))" + Style.RESET_ALL)
        print(Fore.GREEN + "                      \___|___/" + Style.RESET_ALL)
        print(Fore.GREEN + "                    .--' | | '--." + Style.RESET_ALL)
        print(Fore.GREEN + "                    \__._| |_.__/" + Style.RESET_ALL)
    def menu_c(self, text):
        print("         ,/`.             :'''''''''''''':       .---.               ")
        print("       ,'/ __`.             {0}                          ".format(text))
        print("     ,'_/_  _ _`.         :..............:_     \.@-@./                ")
        print("   ,'__/_ ___ _  `.                        '_   /`\_/`\              ")
        print(" ,'_  /___ __ _ __ `.                          //  _  \\                 ")
        print("'-.._/_______________`.                       | \     )|_                ")
        print("                                             /`\_`>  <_/ \                ")
        print("                                             \__/'---'\__/                ")
    def menu_buttons(self):
        print("|''''''''''''''''|")
        print("|1. Начать игру  |")
        print("|................|")
        print("|''''''''''''''''|")
        print("|0. Выйти из игры|")
        print("|................|")
        print("")
    def game(self, warning, diaposon):
        print("       _            ")
        print("       __ -         ")
        print("   /     __   \     ")
        print("     /   _ -    |   ")
        print(" | '  | (_)  |      ")                  
        print("    |  __  /   /    ")                
        print("   \ \  __  /       ")              
        print("       -            ")
        print("         ,/`.             :'''''''''''''':       .---.               ")
        print("       ,'/ __`.           {0}                          ".format(warning))
        print("     ,'_/_  _ _`.         :..............:_     \.@-@./                ")
        print("   ,'__/_ ___ _  `.                        '_   /`\_/`\              ")
        print(" ,'_  /___ __ _ __ `.                          //  _  \\     ")
        print("'-.._/_______________`.  . . .:. . : .        | \     )|_                ")
        print(".:::.:::..:::.;;;;:;;:.;.;;;;:,;;;.;:,;;,;   /`\_`>  <_/ \                ")
        print(". ,::.:::.:..:.: ::.::::;..:,:::,::::.::::.  \__/'---'\__/                ")
        print(".   .:.:::.:::.::::{0}::.::::..::..:.:::.::::..::..:.:".format(diaposon))
        print(".  ::.:.: :. .:::  ::::.::.:::.::...:. .:::. .")
        print("     .:. ..   . ::.. .: ::. ::::.:: ::::::.   .")
        print(".     :.         .. :::.::: ::.::::. ::. .")
        print(".       .           .:. :.. :::. ::..: :.")
        print("                   .:  .:::.:: ::..:  .")
        print("                       . :. .. :. .")
    def chest(self, level_number):
        print("             __________         _....._                    ")
        print("            /\____;;___\       ';-.--';'                   ")
        print("           | /         /         }===={                    ")
        print("           `. ())oo() .        .'      '.                  ")
        print("            |\(%()*^^()^\     /::        \                 ")
        print("            | |-%-------|    |::  $ $ $   :                ")
        print("            \ | %  ))   |    \::.         .                ")
        print("             \|%________|     '::_     _`-                 ")
        print("                                  `````                    ")
        print("   Уровень {0} пройден! Продолжайте в том же духе!  ".format(level_number))
        print("\n\n loading", end="")
        for i in range(3):
            sleep(0.5)
            print(".", end="")
    def death(self, level_number):
        print("                             ______                             ")
        print("                          .-"      "-.                          ")
        print("                         /            \                         ")
        print("                        |              |                        ")
        print("                        |,  .-.  .-.  ,|                        ")
        print("                        | )(__/  \__)( |                        ")
        print("                        |/     /\     \|                        ")
        print("                        (_     ^^     _)                        ")
        print("                         \__|IIIIII|__/                         ")
        print("                          | \IIIIII/ |                          ")
        print("                          \          /                          ")
        print("                           `--------`                           ")
        print("       Вы угодили в ловушку, исчерпав лимит своих попыток!      ")
        print("         Итого, вы погибли на {0} уровне! Попробуйте еще!       ".format(level_number))
        print("\n")
        print("|''''''''''''''''''''''|")
        print("|1. Повторить попытку  |")
        print("|......................|")
        print("|''''''''''''''''''''''|")
        print("|0. Выйти в меню       |")
        print("|......................|")
        print("")
    def stage(self):
        print("|'''''''''''''''''''''''''''''''''''|")
        print("|1. Помотреть обучающий видеоролик  |")
        print("|...................................|")
        print("|'''''''''''''''''''''''''''''''''''|")
        print("|0. Пропустить                      |")
        print("|...................................|")
    def game_intro(self):
        print(Fore.WHITE + "  ╔╦╗╦═╗╦ ╦  ╔╦╗╔═╗  ╔═╗╦ ╦╔═╗╔═╗╔═╗  " + Style.RESET_ALL)
        print(Fore.BLUE +  "   ║ ╠╦╝╚╦╝   ║ ║ ║  ║ ╦║ ║║╣ ╚═╗╚═╗  " + Style.RESET_ALL)  
        print(Fore.RED +   "   ╩ ╩╚═ ╩    ╩ ╚═╝  ╚═╝╚═╝╚═╝╚═╝╚═╝  " + Style.RESET_ALL)
        print(Fore.CYAN + "              ╔═╗╔═╗╔╦╗╔═╗            " + Style.RESET_ALL)
        print(Fore.CYAN + "              ║ ╦╠═╣║║║║╣             "  + Style.RESET_ALL)  
        print(Fore.CYAN + "              ╚═╝╩ ╩╩ ╩╚═╝            " + Style.RESET_ALL)